kind: pipeline
type: docker
name: build-docker

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: publish
    image: plugins/docker
    settings:
      tags: latest
      username:
        from_secret: registry_login
      password:
        from_secret: registry_password
      repo: mythevalentinus/junkmail_api
    commands: []

  - name: send telegram notification
    image: appleboy/drone-telegram
    commands: []
    settings:
      token:
        from_secret: telegram_bot_id
      to:
        from_secret: telegram_channel_id
    when:
      status:
        - success
        - failure
